repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        entry: sh -c 'npm run lint'
        files: .js$
  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        language: system
        entry: sh -c 'npm run lint:style'
        files: .css$
