name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    strategy:
      max-parallel: 2
      matrix:
        node: [ "13", "14", "15" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install

      - name: Build
        run: yarn lerna:build

      - name: Test
        run: yarn lerna:test

      - name: Test
        run: yarn lerna:check

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: hashFiles('./coverage/lcov.info') != ''
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run-${{ matrix.node }}

      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: actions ${{ matrix.node }}
          files: ./core/coverage/coverage-final.json,./api/alieza/coverage/coverage-final.json,./api/caillen/coverage/coverage-final.json,./api/cenobie/coverage/coverage-final.json,./api/domino/coverage/coverage-final.json,./api/jaydin/coverage/coverage-final.json,./api/kilan/coverage/coverage-final.json,./api/norene/coverage/coverage-final.json,./api/ocie/coverage/coverage-final.json,./api/shaena/coverage/coverage-final.json,./api/unity/coverage/coverage-final.json,./api/zylla/coverage/coverage-final.json
          fail_ci_if_error: true
          verbose: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    if: hashFiles('./coverage/lcov.info') != ''
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
