name: cspell-action
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: streetsidesoftware/cspell-action@v1.2.5
